
import React from 'react';
import { Shield } from 'lucide-react';

const Legal = () => {
  return (
    <section id="disclaimer" className="py-24 relative overflow-hidden bg-alchemist-darker">
      <div className="absolute inset-0 bg-alchemist-glow opacity-50"></div>
      
      <div className="container mx-auto px-6 relative z-10">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center py-1 px-3 rounded-full bg-alchemist-purple/20 border border-alchemist-purple/30 mb-4">
            <Shield size={14} className="text-alchemist-gold mr-2" />
            <span className="text-sm font-medium">Legal Information</span>
          </div>
          
          <h2 className="text-3xl md:text-4xl font-medieval font-bold mb-6 text-gradient-primary">
            Legal Disclaimer
          </h2>
          
          <p className="text-gray-300 text-lg">
            Important information regarding the use of Alchemist Scientist GPT.
          </p>
        </div>
        
        <div className="glass-panel rounded-xl p-8 max-w-4xl mx-auto">
          <div className="space-y-6 text-gray-300">
            <div>
              <h3 className="text-xl font-medieval font-semibold mb-3 text-white">Educational Purpose</h3>
              <p>
                Alchemist Scientist GPT is designed for educational and entertainment purposes only. The information provided is meant to enhance understanding of chemistry and historical scientific methods through an immersive and engaging approach.
              </p>
            </div>
            
            <div>
              <h3 className="text-xl font-medieval font-semibold mb-3 text-white">Not Medical or Scientific Advice</h3>
              <p>
                Content generated by Alchemist Scientist GPT should not be considered medical, legal, or professional scientific advice. The alchemical methods described are historical representations and should not be attempted as substitutes for modern scientific practices or treatments.
              </p>
            </div>
            
            <div>
              <h3 className="text-xl font-medieval font-semibold mb-3 text-white">Historical Context vs. Modern Science</h3>
              <p>
                While the AI strives to provide historically accurate representations of medieval alchemy, it also clearly distinguishes between historical beliefs and modern scientific understanding. Users should recognize that the alchemical framework is used as an engaging educational tool, not as scientifically valid methodology by current standards.
              </p>
            </div>
            
            <div>
              <h3 className="text-xl font-medieval font-semibold mb-3 text-white">Safety Warning</h3>
              <p>
                Some alchemical processes described may represent dangerous chemical reactions if attempted physically. Users should never attempt to recreate any described experiments without proper scientific knowledge, equipment, and safety precautions. All experimental descriptions are provided for educational understanding only.
              </p>
            </div>
            
            <div>
              <h3 className="text-xl font-medieval font-semibold mb-3 text-white">Limitation of Liability</h3>
              <p>
                AI Web Tools LLC, its affiliates, partners, and representatives assume no responsibility or liability for any errors or omissions in the content provided by Alchemist Scientist GPT. The information is provided "as is" with no guarantees of completeness, accuracy, usefulness, or timeliness.
              </p>
            </div>
            
            <div>
              <h3 className="text-xl font-medieval font-semibold mb-3 text-white">External Links and Resources</h3>
              <p>
                Any external links provided through Alchemist Scientist GPT are for reference only. AI Web Tools LLC is not responsible for the content of external sites and does not endorse any commercial products that may be advertised or available on linked sites.
              </p>
            </div>
            
            <div className="pt-4 border-t border-white/10">
              <p className="text-sm text-gray-400">
                By using Alchemist Scientist GPT, you acknowledge and agree to these terms and conditions. This disclaimer is subject to change without notice.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Legal;
